### ISSUE TITLE
Cannot read url that has the element "www."

### ISSUE THREAD

**Issue by dewikiswani** [aephidayatuloh/rpubs#1]
I use this url to try the rpubs_code function.

[https://www.rpubs.com/arvindpdmn/r-basics-for-beginners](url)

I can't read urls that have the "www" element. I got an error like this

```
rpubs_code(url = "https://www.rpubs.com/arvindpdmn/r-basics-for-beginners", file = "new.R", output = FALSE)

Error in rpubs_code(url = "https://www.rpubs.com/arvindpdmn/r-basics-for-beginners",  : 
  Only support article from https://rpubs.com`

```
when i remove "www" in url i can run this function

```
rpubs_code(url = "https:/rpubs.com/arvindpdmn/r-basics-for-beginners", file = "new.R", output = FALSE)

```

**Comment by aephidayatuloh** [comment]
Hi @dewikiswani , thanks for this report.
I've updated for this issue. Please check agin by install new version.

```
devtools::install_github("aephidayatuloh/rpubs")
```
